import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import PrefixedLink from "../components/PrefixedLink";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center">
        <div>
          <h1 className="text-4xl font-bold text-center mb-4">단어 퀴즈</h1>
          <div>
            <PrefixedLink href="/quizs/default">퀴즈 이동!</PrefixedLink>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
